server:
  port: 8090
  servlet:
    context-path:

application:
  proxy:
    enabled: true
    host: 192.168.15.10
    port: 8080
    noProxy: localhost|127.0.0.1|*.svc.cluster.local|config-platform-service.platform.svc.cluster.local|s3-minio.storage.svc.cluster.local


spring:
  data:
    rest:
      detection-strategy: annotated
      base-path: v1
  datasource:
    url: jdbc:h2:~/db1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
